### ISSUE TITLE
T1MOH - Protocol assumes DAI is $1

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#714]
T1MOH

high

# Protocol assumes DAI is $1

## Summary
Whitepaper says USSD represents $1. But in rebalance logic it pegs to value of 1 DAI, instead of $1.

## Vulnerability Detail
Let's have a look into rebalance(). When USSD value deviates from 1 DAI, protocol performs algorithmic trades to return peg.
```solidity
    function rebalance() override public {
      uint256 ownval = getOwnValuation();
      (uint256 USSDamount, uint256 DAIamount) = getSupplyProportion();
      if (ownval < 1e6 - threshold) {
        ...
      } else if (ownval > 1e6 + threshold) {
       ...
      }
    }
```

But function `getOwnValuation()` returns price of USSD in terms of DAI. It breaks the core of protocol, pegging USSD to DAI
```solidity
    /// @dev get price estimation to DAI using pool address and uniswap price
    function getOwnValuation() public view returns (uint256 price) {
      (uint160 sqrtPriceX96,,,,,,) =  uniPool.slot0();
      if(uniPool.token0() == USSD) {
        price = uint(sqrtPriceX96)*(uint(sqrtPriceX96))/(1e6) >> (96 * 2);
      } else {
        price = uint(sqrtPriceX96)*(uint(sqrtPriceX96))*(1e18 /* 1e12 + 1e6 decimal representation */) >> (96 * 2);
        // flip the fraction
        price = (1e24 / price) / 1e12;
      }
    }
```
## Impact
USSD is pegged to DAI instead of $1, it violates the core aim of protocol. And also breakes all protocol in case of DAI depegging.

## Code Snippet
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L92-L107
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L70

## Tool used

Manual Review

## Recommendation
In function `getOwnValuation()` convert DAI price into USD using StableOracleDAI.sol

Duplicate of #909

**Comment by T1MOH593** [comment]
Escalate for 10 USDC

This issue should be a duplicate of #909.
#909 tells that oracles return price in USD, when `getOwnValuation()` returns price in DAI. And suggests to peg USSD either to DAI or USD, because mixing adds inconsistency.
In this report I also point out that protocol is pegged to DAI as it uses `getOwnValuation`. While documentation states that USSD is pegged to USD [here](https://github.com/USSDofficial/ussd-whitepaper/blob/main/whitepaper.pdf): 
![image](https://github.com/sherlock-audit/2023-05-USSD-judging/assets/79079180/1a3e8dc5-6b31-437d-a490-0fb3fefe0a57)

And also mitigation is similar: convert return of `getOwnValuation()` to USD

**Comment by ctf-sec** [comment]
Duplicate of #909

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #909

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [T1MOH593](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/714/#issuecomment-1604557482): accepted
