### ISSUE TITLE
curiousapple - PEG could never be restored completely due incorrect derivation for amount to be swapped

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#834]
curiousapple

high

# PEG could never be restored completely due incorrect derivation for amount to be swapped

## Vulnerability Detail
USSD defines rebalance method to keep the peg of 1 USSD = 1 DAI.
If there is deviation, USSD buys or sells USSD to bring back the peg.
However, the amount to be swapped is derived incorrectly and is not as per the AMM curve of the uniswap.
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L92-L107

As you can see on L97 and L104 above, the excess amount is calculated by directly calculating the difference between the DAI amount and the USSD amount, and then dividing it by 2.

This would have worked if uniswap was constant sum amm, `x+y = k` 
However, this is not the case, uniswap is a constant product amm. `x.y=k`
(V3 even complicates this with ticks, but consider that liquidity is spread throughout)
Hence the amount to be swapped can not be `difference/2` directly, it needs to be derived considering constant product instead.

For example 
(Ignore fees for the moment)

1. DAI: 10000, USSD: 9000 
2. Excess DAI: 1000, 
3. Mint 500USSD, and Swap 500 USSD to DAI
**What USSD Protocol expects to happen** 
DAI: 9500, USSD : 9500 
PEG restores 

**What actually happens on uniswap pool** 
DAI: 9473.68421053, USSD : 9500 (9473.68421053 * 9500 = 9 * 10**8)
PEG is not restored 
And you need to rebalance again, since the deviation is still more than the threshold 
(9473.68421053/9500 = 0.9972299169 => 0.9972299169 * 10 ** 6 > 1e6-1e4)

**Instead of difference, USSD should calculate the amount to be swapped using the constant product formula.**
For example, for the example mentioned above 
It should be
`Sqrt(K) - USSDAmount`
Sqrt(10000*9000) - 9000 = 9486.832981 - 9000 = 486.832
Mint 486.832 USSD, and Swap 486.832 USSD to DAI
DAI: 9486.832, USSD : 9486.832
PEG restored

## Impact
- As per current calculations PEG would never restore.
- Once redemption is enabled, this would allow easy arbitrage
(Sponsor confirmed in DM that redemption is planned, and would be enabled in next version)

## Tool used

Manual Review

## Recommendation
Consider deriving the amount to be swapped in coherence with uniswap's amm.
Since you are using uniswap v3, you also need to consider ticks while calculating excess, different tick ranges can have different amounts of liquidity.

Duplicate of #808

**Comment by abhishekvispute** [comment]
Escalate for 10 USDC

Title: Incorrect Exclusion 

## Overview
For any stablecoin protocol the most important thing is to restore the peg once it's moved.
USSD tries to achieve this using `rebalance` action where they either sell USSD or buy it from uniswap pool to restore the peg there.
However the calculation done for the to-be-swapped amount is wrong, as described in the issue, hence USSD peg not being able to restore completely forever.

## Re-Explanation of cause

**If the example inside the issue is not clear, let me explain it in more detail.**

Uniswap is a constant product AMM, where V2 follows the `XY=K` curve and V3 follows the same curve but with concentrated liquidity between ticks.
Let's consider the XYK curve without fees to keep the calculation simple, however, the same could be used for V3 as well, just the horizon gets limited to the current tick range.

If the given pool has 1000000 (1M) worth of token A (DAI) and 900000 (900K) worth of token B (USSD), 
USSD mints and swaps 50000 worth of token B into token A in hopes of making both reserves the same and to restore it to 1 .

The exact line is https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/USSDRebalancer.sol#L97

However, that's incorrect, doing so won't restore the peg 
 ```
(1000000 - swapOut) * (900000 + 50000) = 1000000 * 900000
(1000000 - swapOut)  = 947368.421053
swapOut = 52631.5789474

reserve A  = 947368.421053
reserve B  = 950000
```
since reserve A != reserve B, the peg is not restored
_with an increase in amounts and depeg, this diff between reserves would increase only._

Instead, USSD should have derived the to-be-swapped amount in accordance with to AMM curve
For a simple example of Uni V2 or UniV3 with an infinite range, it is 

`Sqrt(K) - USSDAmount`
`Sqrt(1000000*900000) - 900000` = `948683.2981 - 900000` = `48683.29805`

Doing this makes both reserves, exactly equal and hence restoring the peg
```
(1000000-swapOut) *  (900000 + 48683.29805) = 1000000 * 900000
swapOut is `51316.7019`
```
which makes both reserves of token A and token B exactly equal restoring the peg
```
reserves A = 1000000 - 51316.7019 = 948683.2981
reserves B = 900000 + 48683.29805 =948683.2981
```

## Re-Explanation of impact
The impact here is USSD not being able to repeg to 1 as expected from protocol, for any stablecoin protocol that's most the important thing.
However, since you are only interested in the loss of assets :), that would happen as well once USSD allows redeems.
Once redeem enabled, this would present easy arbitrage and would create a spiral.
The sponsor accepted in DM that they are going to implement iredeem in the next version and even better sherlock itself has recommended them to do so by issuing https://github.com/sherlock-audit/2023-05-USSD-judging/issues/958 

You can reach me at @curiousapple on discord or telegram if you need more details.

Thanks

**Comment by ctf-sec** [comment]
(Incorrect) Duplicate of https://github.com/sherlock-audit/2023-05-USSD-judging/issues/714, which is duplicate of #909

**Comment by 0xcuriousapple** [comment]
Please consider revisiting your duplication 
The **cause** and **resolution** both are different 

This issue talks about the incorrect derivation of the amount to be swapped due to incorrect accounting of uniswap's curve. (Wrong consideration of it being constant sum AMM instead of constant product AMM)

The issues you have tagged as duplicates talk about the incorrect derivation of the amount to be swapped due to the incorrect use of base currency for Oracle. (Wrong consideration of USD in place of DAI)

Solving one of them doesn't solve another as well.
Both need to be handled differently

**Comment by ctf-sec** [comment]
> Please consider revisiting your duplication The **cause** and **resolution** both are different
> 
> This issue talks about the incorrect derivation of the amount to be swapped due to incorrect accounting of uniswap's curve. (Wrong consideration of it being constant sum AMM instead of constant product AMM)
> 
> The issues you have tagged as duplicates talk about the incorrect derivation of the amount to be swapped due to the incorrect use of base currency for Oracle. (Wrong consideration of USD in place of DAI)
> 
> Solving one of them doesn't solve another as well. Both need to be handled differently

Issue #714 is different from this issue

https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-considered-valid

> Future issues: Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues.

the redeem not abled, but I agree the math is flawed, recommend severity level medium / low (towards medium)

**Comment by hrishibhat** [comment]
@abhishekvispute 
The underlying issue can be considered a duplicate of #808. What do you think?

**Comment by 0xcuriousapple** [comment]
yep both have the same cause

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #808

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [abhishekvispute](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/834/#issuecomment-1606139448): accepted
