### ISSUE TITLE
neumo - BuyUSSDSellCollateral should not burn the whole USSD contract balance

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#902]
neumo

high

# BuyUSSDSellCollateral should not burn the whole USSD contract balance

## Summary
Function `BuyUSSDSellCollateral` is called in contract `USSDRebalancer` to control the peg of USSD to DAI. But it burns the whole USSD balance in the `USSD` contract instead of just the USSD received from selling DAI.

## Vulnerability Detail
As explained in the summary, this fact opens up a price manipulation attack where an attacker can send an arbitrary amount of USSD to the USSD contract, knowing that a call to rebalance will burn much more USSD than intended, thus affecting USSD's price.

In the last lines of the function:
```solidity
...
if (DAItosell > 0) {
	if (uniPool.token0() == USSD) {
		IUSSD(USSD).UniV3SwapInput(bytes.concat(abi.encodePacked(uniPool.token1(), hex"0001f4", uniPool.token0())), DAItosell);
	} else {
		IUSSD(USSD).UniV3SwapInput(bytes.concat(abi.encodePacked(uniPool.token0(), hex"0001f4", uniPool.token1())), DAItosell);
	}
}

IUSSD(USSD).burnRebalancer(IUSSD(USSD).balanceOf(USSD));
...
```
 We see that the call to `burnRebalancer` effectively burns the whole `USSD` contract balance, instead of the USSD resulting from the previous swap.
## Impact
High.

## Code Snippet
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L97
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#LL152C7-L160C63

## Tool used
Manual review.

## Recommendation
Make function `BuyUSSDSellCollateral` receive an `amount` parameter, to just burn the amount received from the swap, not the whole balance.

**Comment by neumoxx** [comment]
Escalate for 10 USDC
The protocol is meant to only allow burning USSD through the rebalancer (if we omit the flagrant bug of lack of `onlyRebalancer` modifier in function `burnRebalancer`). But the issue I flag in my report allows anyone to send USSD tokens to the USSD contract and, after a call to `rebalance()` that triggers the internal call to `BuyUSSDSellCollateral`, the tokens sent to the USSD contract would be burnt along with those that were returned from the interaction with UNISWAP. 

This issue, besides allowing anyone to burn their tokens (which sould not be possible), allows them to impact the price of USSD, eventually forcing a depeg, because burning tokens contracts the supply, making the price go up.

This is, in my opinion, a valid high, I don't understand why was it excluded by the judge, please @hrishibhat give it a read.

**Comment by hrishibhat** [comment]
@ctf-sec

**Comment by ctf-sec** [comment]
duplicate of https://github.com/sherlock-audit/2023-05-USSD-judging/issues/897

**Comment by ctf-sec** [comment]
Actually this would require manipulating the underlying liquidity pool

**Comment by ctf-sec** [comment]
In the current state of the code

```solidity
burnRebalancer
```

lack access control so the USSD can be burned by anyone anyway

I don't think force price to go up is a issue

+ the attacker needs to acquire USSD somewhere and lose fund

**Comment by neumoxx** [comment]
What do you mean manipulating the liquidity pool? As I see it, any whale willing to destroy the USSD project (maybe a competitor) can just burn their tokens and force a depeg, potentially killing the protocol.

**Comment by ctf-sec** [comment]
> What do you mean manipulating the liquidity pool? As I see it, any whale willing to destroy the USSD project (maybe a competitor) can just burn their tokens and force a depeg, potentially killing the protocol.

it is very difficult to measure the impact:

> force USSD to depeg and make the price go up

I can only think the attacker lose the fund that buy the USSD in Uniswap Pool

**Comment by neumoxx** [comment]
> lack access control so the USSD can be burned by anyone anyway

Well, I think we can agree users are not supposed to burn tokens, otherwise why is #777 accepted? What sense would it have to accept #777 as high and discard this issue if both mean users can arbitrarily burn their tokens.

> it is very difficult to measure the impact

I agree, because the price movement of burning the tokens I don't know what would exactly be, maybe the attacker could burn tokens and arbitrage himself taking a profit. What I know is issue #777 is high, and this one has a similar impact (if not same).

**Comment by hrishibhat** [comment]
@neumoxx 
In this case, someone would have lose a large amount of USSD just to be able to depeg, correct?

**Comment by neumoxx** [comment]
@hrishibhat I don't see it this way. It _could_ make some profit for the attacker. 
Imagine the following scenario:
* Attacker burns 100,000 USSD sending them to the contract and forcing a rebalance.
* Price in the UNI pool goes up to 1.2 DAI
* Finally, attacker arbitrages the same price update he forced in the first step, swapping 1,000,000 DAI for 1,200,000 USSD in a CRV pool.

I know the attacker can be frontrun, and it would be a very risky move, but anyway, the possibility itself that a user can force a depeg would be very negative for the protocol, causing fear to its depositors, and bad reputation for the project. This is why **users should never be able to burn tokens**: because it would affect the token price, and so it should only done by the rebalancer. 

This in fact is the same impact than that of #777. In that issue you can also ask: **what benefit has the user burning his tokens?** No benefit at all, he would lose funds, but it would be very negative for the protocol, and that is why its a high.

**Comment by hrishibhat** [comment]
@neumoxx 
The only reason #777 is high because it allows the attacker to 
> alter totalSupply, which is used in rebalancer.SellUSSDBuyCollateral to calculate ownval
This issue seems like a low.

**Comment by neumoxx** [comment]
And here totalSupply would be altered too, no? Maybe I'm missing something, sorry if that's the case.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low, comment from the Lead watson:

In the impact section of #777 
> An attacker can mint an amount of type(uint256).max - totalSupply() and cause a denial-of-service attack by preventing anyone else from minting.

> Additionally, minting will also change the totalSupply which alters the collateralFactor and cause the rebalancer to malfunction, as the SellUSSDBuyCollateral() function relies on the USSD.collateralFactor().

> The totalSupply is also used in rebalancer.SellUSSDBuyCollateral to calculate the ownval.
That's not possible when you can only burn your own USSD

For this issue, to burn $1M USSD of your own, you have to mint 1M USSD or buy 1M USSD which other people minted, then transfer to the contract and burn them

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [neumoxx](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/902/#issuecomment-1605391589): rejected
